version: "1"

services:
  nginx_portfolio_front:
    build:
      context: ./
    container_name: nginx-portfolio-front
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.tesseractmaks.tech`)"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  default:
    name: proxynet
    external: true


